### ISSUE TITLE
OrtSessionHandler.hpp:15:20: fatal error: optional: No such file or directory

### ISSUE THREAD

**Issue by tcxia** [xmba15/onnx_runtime_cpp#1]
#include <onnxruntime/core/providers/cuda/cuda_provider_factory.h>
#include <onnxruntime/core/session/onnxruntime_cxx_api.h>
因为这两个文件报错?

**Comment by xmba15** [comment]
Hi,
Have you used my script to install onnxruntime from source?

Also in CmakeLists you also need to specify onnxruntime_INCLUDE_DIRS, like this
```
set(onnxruntime_INSTALL_PREFIX /usr/local)
set(onnxruntime_INCLUDE_DIRS
  ${onnxruntime_INSTALL_PREFIX}/include/onnxruntime
  ${onnxruntime_INSTALL_PREFIX}/include/onnxruntime/core/session
)
```
and include it

**Comment by tcxia** [comment]
@xmba15  我已经安装了，但是#include<optional>这个文件找不到，好像只能C++17才可以

**Comment by tcxia** [comment]
我已经安装了，但是#include<optional>这个文件找不到，好像只能C++17才可以

**Comment by tcxia** [comment]
I have installed it, but I can't find the #include<optional> file. It seems to be C++17 only!

**Comment by xmba15** [comment]
yes. I have used some small functions (std::optional) of C++17, so currently support C++17 only. Those parts of C++17 can be rewritten into C++11 actually. If you just want to test how onnxruntime work, maybe you can first try with C++17.

**Comment by tcxia** [comment]
@xmba15 I've already rewritten it for c++14. I'll test it later. Thank you

**Comment by xmba15** [comment]
I will close the PR now. Feel free to open it again if troubles happen.

**Comment by kennyvoo** [comment]
@tcxia Hello, Do you mind sharing what did you change  to compile it in C++14?

**Comment by kennyvoo** [comment]
Solved. Just in case anyone need.
 
std::optional  to boost::optional
std::nullopt to boost::none
.has_value to .is_initialized()
