### ISSUE TITLE
[install_onnx_runtime.sh] Build Error: need to install cuda package

### ISSUE THREAD

**Issue by cardboardcode** [xmba15/onnx_runtime_cpp#2]
Hi xmba15, thank you for creating this C++ library for running onnxruntime. 

This issue has been resolved. This post is only to record a frequent error I faced as well as the remedy for it. 

## Issue Description
Running the command as shown in `README.md`,
> sudo bash ./scripts/install_onnx_runtime.sh
generates the build failure showing the following error in terminal:
>/usr/bin/env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
-------------------------------------------------------------------------
checking dependencies...
-------------------------------------------------------------------------
need to install cuda package

This error is caused because the command **nvcc** fails to execute based on the script. 

If like me, running `nvcc -V` in terminal works fine but the error persists, do the following to resolve the issue. 

## Solution
After [line 5 of install_onnx_runtime.sh](https://github.com/xmba15/onnx_runtime_cpp/blob/0686b9db0b170c2b07e8d8b9edabc9e3791aba11/scripts/install_onnx_runtime.sh#L5), add the following lines.

```
export CUDA_HOME=/usr/local/cuda
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64
export PATH=$PATH:$CUDA_HOME/bin
```

**Comment by xmba15** [comment]
@cardboardcode sorry i didnt notice this issue before...

**Comment by 205418367** [comment]
必须要安装cuda吗？

**Comment by xmba15** [comment]
@205418367 yes, cuda and cudnn need to be installed beforehand.
