### ISSUE TITLE
pipline  for superpoint

### ISSUE THREAD

**Issue by bb67ao** [xmba15/onnx_runtime_cpp#33]
could you please show me the pipline about superpoint，I faced some problems when inferenced my superpoint.onnx.so I hope to get inspired from your code

**Comment by xmba15** [comment]
@bb67ao here is how you build and run the model.
https://github.com/xmba15/onnx_runtime_cpp/issues/34

**Comment by bb67ao** [comment]
good work ,thanks a lot
