### ISSUE TITLE
how to build?

### ISSUE THREAD

**Issue by Joevaen** [xmba15/onnx_runtime_cpp#34]
Where should I build from? Can you explain it in detail? For example, how to run yolov3app?
Thanks!

**Comment by xmba15** [comment]
@Joevaen Do you use docker? That should be the fastest way you can reproduce the result for all the apps in this repo, because if you directly build using the scripts I provided locally, it might mess with the softwares you already have in your system.

Here is the procedure to build using the dockerfile I already prepared for a CPU system:

```bash
# cd /to/this/repo

# build docker image, this will install all the depedencies
docker build -f ./dockerfiles/ubuntu2004.dockerfile -t onnx_runtime .

# start a docker container
docker run -it --rm -v `pwd`:/workspace onnx_runtime

# inside docker, build apps with
make apps

# download yolov3 models from 
# https://github.com/onnx/models/tree/main/vision/object_detection_segmentation/yolov3

# run the app with
./build/examples/yolov3 [path/to/yolov3/onnx/model] ./data/images/no_way_home.jpg
```

**Comment by xmba15** [comment]
If you don't use docker, and want to build directly in your local system. Here is how you build the apps for CPU.

```bash
# cd /to/this/repo

bash ./scripts/install_latest_cmake.bash

bash ./scripts/install_onnx_runtime.bash

bash ./scripts/install_onnx_runtime.bash

# inside docker, build apps with
make apps

# download yolov3 models from 
# https://github.com/onnx/models/tree/main/vision/object_detection_segmentation/yolov3

# run the app with
./build/examples/yolov3 [path/to/yolov3/onnx/model] ./data/images/no_way_home.jpg
```

But as I mentioned above, there might be conflict with your local environment, you need to check the contents of the 3 bash scripts above.

**Comment by Joevaen** [comment]
Thanks, I have figured out. Actually, I need delete last line in cmakelist.
