### ISSUE TITLE
if  the superpoint and superglue use cuda when inference？ i can't find the cuda information in the code? could you please explain it , thanks !

### ISSUE THREAD

**Issue by sanersbug** [xmba15/onnx_runtime_cpp#36]

**Comment by xmba15** [comment]
Hi @sanersbug 
You can follow this instruction
https://github.com/xmba15/onnx_runtime_cpp/issues/34

But instead of using **ubuntu2004.dockerfile**, use  [ubuntu2004_gpu.dockerfile](https://github.com/xmba15/onnx_runtime_cpp/blob/master/dockerfiles/ubuntu2004_gpu.dockerfile) for inference with gpu.

**Comment by sanersbug** [comment]
@xmba15 OK，thanks,  i solved it .
another thing that i find  LoFTR and Lisrd have a better effect and more stable than superpoint and superglue , if you can do it with onnxruntime, even better .
