### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by qazzombie** [xmba15/onnx_runtime_cpp#42]
when I  run make apps , have some error :
/Users/admin/Desktop/onnx_runtime_cpp-master/include/ort_utility/Utility.hpp:92:26: error: no viable conversion from 'deque<size_t>' to 'deque<uint64_t>'
    std::deque<uint64_t> sortedIndices = ::sortIndexes(scores);
/Users/admin/Desktop/onnx_runtime_cpp-master/include/ort_utility/Utility.hpp:123:45: error: type 'const std::array<float, 4>' does not provide a subscript operator
            float tmpXmin = std::max(curBbox[0], bbox[0]);
/Users/admin/Desktop/onnx_runtime_cpp-master/include/ort_utility/Utility.hpp:124:45: error: type 'const std::array<float, 4>' does not provide a subscript operator
            float tmpYmin = std::max(curBbox[1], bbox[1]);
...........
how to deal it ?

**Comment by xmba15** [comment]
Let's use docker for easier reproduction of the results.
https://github.com/xmba15/onnx_runtime_cpp/issues/34

**Comment by qazzombie** [comment]
> Let's use docker for easier reproduction of the results. #34

but mine is macos ,is this ubuntu-dockerfile suitable for me to docker build

**Comment by xmba15** [comment]
Well you need customize dockers suitable for your OS then.

**Comment by qazzombie** [comment]
> 

Well,thank you for your reply
