### ISSUE TITLE
Error about OrtSessionHandler.cpp

### ISSUE THREAD

**Issue by x12901** [xmba15/onnx_runtime_cpp#5]
https://github.com/xmba15/onnx_runtime_cpp/blob/91087083e5aa898eac84e7087049f50f1dceb064/src/OrtSessionHandler.cpp#L204 
I'm trying to compile programs under win10.I use this runtime package.
https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime.gpu
Then it reported an error.
`Severity Code Description Item File Line Disabled Display Status Details
Error (active) E0289 No constructor "Ort::Session::Session" instance ort_utility D:\CODE\onnx_runtime_cpp\src\OrtSessionHandler.cpp 204 Parameters of type: ( Ort::Env, const char *, Ort::SessionOptions)
`
In onnxruntime_cxx_api.h, the parameter types seem to be different from the ones used.
```
struct Session : Base<OrtSession> {
  explicit Session(std::nullptr_t) {}
  Session(Env& env, const ORTCHAR_T* model_path, const SessionOptions& options);
  Session(Env& env, const void* model_data, size_t model_data_length, const SessionOptions& options);
```

**Comment by xmba15** [comment]
@x12901 in _WIN32, ORTCHAR_T is defined as 
#define ORTCHAR_T wchar_t
https://github.com/microsoft/onnxruntime/blob/v1.5.3/include/onnxruntime/core/session/onnxruntime_c_api.h#L55

Can you try 
```cpp
   std::wstring modelPathWstr = std::wstring(str.begin(), str.end());
   m_session = Ort::Session(m_env, modelPathWstr.c_str(), sessionOptions); 
```

**Comment by xmba15** [comment]
@x12901 also, if you target both windows and linux, you have to use macro flag to separate each environment then.

**Comment by xmba15** [comment]
@x12901 Can you test if it works?
For now, I will close this issue; feel free to open it again.
