### ISSUE TITLE
在哪个位置执行编译？

### ISSUE THREAD

**Issue by zhb0920** [xmba15/onnx_runtime_cpp#6]
/onnx_runtime_cpp/build$ 下面执行
```
cmake ..
make all
```
报错
`[ 20%] Building CXX object src/CMakeFiles/ort_utility.dir/ImageClassificationOrtSessionHandler.cpp.o
In file included from /home/zhb/pytorch_project/onnx_runtime_cpp/./include/ort_utility/ImageRecognitionOrtSessionHandlerBase.hpp:16:0,
                 from /home/zhb/pytorch_project/onnx_runtime_cpp/./include/ort_utility/ImageClassificationOrtSessionHandler.hpp:16,
                 from /home/zhb/pytorch_project/onnx_runtime_cpp/./include/ort_utility/ort_utility.hpp:14,
                 from /home/zhb/pytorch_project/onnx_runtime_cpp/src/ImageClassificationOrtSessionHandler.cpp:14:
/home/zhb/pytorch_project/onnx_runtime_cpp/./include/ort_utility/OrtSessionHandler.hpp:15:20: fatal error: optional: No such file or directory
compilation terminated.
src/CMakeFiles/ort_utility.dir/build.make:62: recipe for target 'src/CMakeFiles/ort_utility.dir/ImageClassificationOrtSessionHandler.cpp.o' failed
make[2]: *** [src/CMakeFiles/ort_utility.dir/ImageClassificationOrtSessionHandler.cpp.o] Error 1
CMakeFiles/Makefile2:90: recipe for target 'src/CMakeFiles/ort_utility.dir/all' failed
make[1]: *** [src/CMakeFiles/ort_utility.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by xmba15** [comment]
Sorry can you please explain the problem in English?

**Comment by Joevaen** [comment]
> Sorry can you please explain the problem in English?

I have the same question: where should I build from if I want to run yolov3app? The doc didn't explain in detail.
