### ISSUE TITLE
 linked by target "ort_utility" in directory 

### ISSUE THREAD

**Issue by DYF-AI** [xmba15/onnx_runtime_cpp#7]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
onnxruntime_LIBS
    linked by target "ort_utility" in directory /source/code/AI/src/inference/OnnxRT/CppDeploy/samples/onnx_runtime_cpp/src

-- Configuring incomplete, errors occurred!
See also "/source、code/AI/src/inference/OnnxRT/CppDeploy/samples/onnx_runtime_cpp/build/CMakeFiles/CMakeOutput.log".
Makefile:7: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by xmba15** [comment]
@DYF-AI Can you elaborate more details about your build errors? Did you install onnxruntime using the scripts I provided in this repository?

**Comment by DYF-AI** [comment]
I solved the problem. How much faster is cpp than py? My experiment is that cpp is only a little bit faster than py

**Comment by xmba15** [comment]
@DYF-AI in theory, onnxruntime is only inference engine, so the speed will not change with the version in python gpu, unless you model is converted in tensorrt. However, this repository does not cover tensorrt.
